name: "Comment with Changes Breakdown"
on:
  pull_request:
    branches:
      - master
      - '**'
  push:

jobs:
  comment:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: MercuryTechnologies/paths-filter@28cec18b46897a4b31b6003a92d5dcda39c9078f
      id: filter
      with:
        stat: json
        filters: |
          src:
            - action.yml
          docs:
            - "**/*.md"
    - uses: ./
      with:
        diff-stat: ${{ steps.filter.outputs.stat }}
